Resources:
  DrinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
        - "AttributeName": "name"
          "AttributeType": "S"
        - "AttributeName": "userId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Drinks"
      GlobalSecondaryIndexes:
        - IndexName: "UserIdIndex"
          KeySchema:
            - AttributeName: "userId"
              KeyType: "HASH"
            - AttributeName: "name"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL