Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - "AttributeName": "userId"
          "AttributeType": "S"
        - "AttributeName": "drink"
          "AttributeType": "S"
        "KeySchema":
        - "AttributeName": "userId"
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: false
          BillingMode: PAY_PER_REQUEST
          TableName: "User"
